# Generated by Django 3.1.3 on 2020-11-13 18:37

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='conteudo',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='resumo',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
