# Generated by Django 3.1.3 on 2020-11-18 20:12

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postblog', '0002_auto_20201113_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='foto',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='resumo',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
